// This file is auto-generated — do not edit manually.
import type { IkasImage } from "@ikas/bp-storefront";

export interface Props {
  sectionAnchorId?: string;
  proofCategory1?: string;
  proofCategory2?: string;
  trustLogo4ImageUrl?: IkasImage | null;
  proofCategory3?: string;
  proofCategory4?: string;
  proofMetric1Value?: string;
  proofMetric1Label?: string;
  proofMetric2Value?: string;
  proofMetric2Label?: string;
  proofMetric3Value?: string;
  proofMetric3Label?: string;
  actionsAriaLabel?: string;
  proofAriaLabel?: string;
  logosAriaLabel?: string;
  trustLogo1ImageUrl?: IkasImage | null;
  trustLogo2ImageUrl?: IkasImage | null;
  trustLogo3ImageUrl?: IkasImage | null;
  proofDescription?: string;
  proofTitle?: string;
  trustLogo5ImageUrl?: IkasImage | null;
  eyebrowText?: string;
  titleText?: string;
  descriptionHtml?: string;
  proofEyebrow?: string;
  primaryButtonText?: string;
  primaryButtonHref?: string;
  secondaryButtonText?: string;
  secondaryButtonHref?: string;
  proofEyebrowEn?: string;
  logosAriaLabelEn?: string;
  proofAriaLabelEn?: string;
  actionsAriaLabelEn?: string;
  proofMetric3LabelEn?: string;
  proofMetric1LabelEn?: string;
  proofMetric2LabelEn?: string;
  descriptionHtmlEn?: string;
  secondaryButtonTextEn?: string;
  proofTitleEn?: string;
  primaryButtonTextEn?: string;
  proofDescriptionEn?: string;
  proofCategory1En?: string;
  titleTextEn?: string;
  eyebrowTextEn?: string;
  proofCategory2En?: string;
  proofCategory3En?: string;
  proofCategory4En?: string;
  paddingTop?: number;
  lineColor?: string;
  backgroundColor?: string;
  textColor?: string;
  mutedTextColor?: string;
  paddingBottom?: number;
  maxWidth?: number;
  showActions?: boolean;
  showProofSummary?: boolean;
  showTrustLogos?: boolean;
  showPrimaryButton?: boolean;
  showSecondaryButton?: boolean;
}
