// This file is auto-generated — do not edit manually.
import type { IkasImage } from "@ikas/bp-storefront";

export interface Props {
  eyebrowText?: string;
  titleText?: string;
  descriptionHtml?: string;
  card1Title?: string;
  card1Text?: string;
  card2Title?: string;
  card2Text?: string;
  card3Title?: string;
  card3Text?: string;
  primaryButtonText?: string;
  primaryButtonHref?: string;
  secondaryButtonText?: string;
  secondaryButtonHref?: string;
  backgroundColor?: string;
  textColor?: string;
  mutedTextColor?: string;
  panelColor?: string;
  accentColor?: string;
  lineColor?: string;
  wordStyleEnabled?: boolean;
  styledPhrase?: string;
  styledPhraseColor?: string;
  styledPhraseBold?: boolean;
  styledPhraseItalic?: boolean;
  quoteAuthorText?: string;
  introTitleText?: string;
  /** Canlı Mash Academy sayfasındaki sağ büyük görsel. */
  introImageUrl?: IkasImage | null;
  introImageAlt?: string;
  showIntroImage?: boolean;
  event1ImageUrl?: IkasImage | null;
  event1ImageAlt?: string;
  event1Date?: string;
  event2ImageUrl?: IkasImage | null;
  event2ImageAlt?: string;
  event2Date?: string;
  showPastSection?: boolean;
  showEventCards?: boolean;
  quoteTextColor?: string;
  quoteAuthorColor?: string;
  headingColor?: string;
  introBackgroundColor?: string;
  introTextColor?: string;
  cardTitleColor?: string;
  eventDateColor?: string;
  eventImageBackgroundColor?: string;
  readMoreColor?: string;
  maxContentWidth?: number;
  quoteWidthPercent?: number;
  quoteMinWidth?: number;
  quotePadding?: number;
  sectionGap?: number;
  introImageWidthVw?: number;
  introImageMaxWidth?: number;
  introImageMinHeight?: number;
  eventCardsGap?: number;
  eventImageRatio?: string;
}
