// This file is auto-generated — do not edit manually.
import type { IkasProductList, IkasImage } from "@ikas/bp-storefront";

export interface Props {
  /** Kaynak Canlı Ürünler seçiliyken kullanılır. */
  productList?: IkasProductList;
  /** products veya manual yazın. manual seçilirse mağaza ürünleri yerine manuel kartlar kullanılır. */
  sliderSource?: string;
  sectionAnchorId?: string;
  setupMessage?: string;
  carouselAriaLabel?: string;
  ctaText?: string;
  descriptionMaxLength?: number;
  showIntro?: boolean;
  introTitle?: string;
  introDescriptionHtml?: string;
  /** left, center veya right yazın. */
  introAlign?: string;
  introMaxWidth?: number;
  introSpacing?: number;
  introTitleFontSize?: number;
  introBodyFontSize?: number;
  showCategoryTag?: boolean;
  showDescription?: boolean;
  showSpecs?: boolean;
  showCta?: boolean;
  manualCardCount?: number;
  manualCard1Enabled?: boolean;
  manualCard1ImageUrl?: IkasImage | null;
  manualCard1ImageAlt?: string;
  manualCard1Tag?: string;
  manualCard1Title?: string;
  manualCard1DescriptionHtml?: string;
  manualCard1Spec1Label?: string;
  manualCard1Spec1Value?: string;
  manualCard1Spec2Label?: string;
  manualCard1Spec2Value?: string;
  manualCard1CtaText?: string;
  manualCard1CtaHref?: string;
  manualCard2Enabled?: boolean;
  manualCard2ImageUrl?: IkasImage | null;
  manualCard2ImageAlt?: string;
  manualCard2Tag?: string;
  manualCard2Title?: string;
  manualCard2DescriptionHtml?: string;
  manualCard2Spec1Label?: string;
  manualCard2Spec1Value?: string;
  manualCard2Spec2Label?: string;
  manualCard2Spec2Value?: string;
  manualCard2CtaText?: string;
  manualCard2CtaHref?: string;
  manualCard3Enabled?: boolean;
  manualCard3ImageUrl?: IkasImage | null;
  manualCard3ImageAlt?: string;
  manualCard3Tag?: string;
  manualCard3Title?: string;
  manualCard3DescriptionHtml?: string;
  manualCard3Spec1Label?: string;
  manualCard3Spec1Value?: string;
  manualCard3Spec2Label?: string;
  manualCard3Spec2Value?: string;
  manualCard3CtaText?: string;
  manualCard3CtaHref?: string;
  manualCard4Enabled?: boolean;
  manualCard4ImageUrl?: IkasImage | null;
  manualCard4ImageAlt?: string;
  manualCard4Tag?: string;
  manualCard4Title?: string;
  manualCard4DescriptionHtml?: string;
  manualCard4Spec1Label?: string;
  manualCard4Spec1Value?: string;
  manualCard4Spec2Label?: string;
  manualCard4Spec2Value?: string;
  manualCard4CtaText?: string;
  manualCard4CtaHref?: string;
  manualCard5Enabled?: boolean;
  manualCard5ImageUrl?: IkasImage | null;
  manualCard5ImageAlt?: string;
  manualCard5Tag?: string;
  manualCard5Title?: string;
  manualCard5DescriptionHtml?: string;
  manualCard5Spec1Label?: string;
  manualCard5Spec1Value?: string;
  manualCard5Spec2Label?: string;
  manualCard5Spec2Value?: string;
  manualCard5CtaText?: string;
  manualCard5CtaHref?: string;
  manualCard6Enabled?: boolean;
  manualCard6ImageUrl?: IkasImage | null;
  manualCard6ImageAlt?: string;
  manualCard6Tag?: string;
  manualCard6Title?: string;
  manualCard6DescriptionHtml?: string;
  manualCard6Spec1Label?: string;
  manualCard6Spec1Value?: string;
  manualCard6Spec2Label?: string;
  manualCard6Spec2Value?: string;
  manualCard6CtaText?: string;
  manualCard6CtaHref?: string;
  manualCard7Enabled?: boolean;
  manualCard7ImageUrl?: IkasImage | null;
  manualCard7ImageAlt?: string;
  manualCard7Tag?: string;
  manualCard7Title?: string;
  manualCard7DescriptionHtml?: string;
  manualCard7Spec1Label?: string;
  manualCard7Spec1Value?: string;
  manualCard7Spec2Label?: string;
  manualCard7Spec2Value?: string;
  manualCard7CtaText?: string;
  manualCard7CtaHref?: string;
  manualCard8Enabled?: boolean;
  manualCard8ImageUrl?: IkasImage | null;
  manualCard8ImageAlt?: string;
  manualCard8Tag?: string;
  manualCard8Title?: string;
  manualCard8DescriptionHtml?: string;
  manualCard8Spec1Label?: string;
  manualCard8Spec1Value?: string;
  manualCard8Spec2Label?: string;
  manualCard8Spec2Value?: string;
  manualCard8CtaText?: string;
  manualCard8CtaHref?: string;
  maxWidth?: number;
  paddingTop?: number;
  paddingBottom?: number;
  visibleCardsDesktop?: number;
  visibleCardsTablet?: number;
  cardGap?: number;
  cardRadius?: number;
  carouselDurationSeconds?: number;
  pauseOnHover?: boolean;
  edgeFadeWidth?: number;
  productImageWidth?: number;
  productImageHeight?: number;
  productImageXOffset?: number;
  productImageYOffset?: number;
  /** contain, cover, fill veya scale-down. */
  productImageFit?: string;
  productImageOpacity?: number;
  productImageBrightness?: number;
  productImageContrast?: number;
  productImageSaturation?: number;
  productImageHue?: number;
  productImageInvert?: number;
  backgroundColor?: string;
  textColor?: string;
  subTextColor?: string;
  mutedTextColor?: string;
  lineColor?: string;
  panelColor?: string;
  accentColor?: string;
  accentTextColor?: string;
  cardMediaStartColor?: string;
  cardMediaEndColor?: string;
}
