// This file is auto-generated — do not edit manually.
import type { IkasProduct } from "@ikas/bp-storefront";

export interface Props {
  /** Aktif olduğunda bu bölüm, seçili ürün veya sayfa ürünü için aşağıdaki ürün bazlı ayarları kullanır. */
  productBasedEnabled?: boolean;
  /** Spesifik ürün seçebilir veya bu alanın kendi Sayfanın ürününü kullan seçeneğini açarak mevcut ürün sayfasına otomatik bağlayabilirsin. */
  product?: IkasProduct | null;
  /** Sayfa içi link için id. Boş bırakılabilir. */
  productBasedSectionAnchorId?: string;
  /** En fazla 6 metrik render edilir. */
  productBasedMetricCount?: number;
  productBasedMetric1Enabled?: boolean;
  productBasedMetric1Value?: string;
  productBasedMetric1Unit?: string;
  productBasedMetric1Title?: string;
  productBasedMetric1Subtitle?: string;
  productBasedMetric2Enabled?: boolean;
  productBasedMetric2Value?: string;
  productBasedMetric2Unit?: string;
  productBasedMetric2Title?: string;
  productBasedMetric2Subtitle?: string;
  productBasedMetric3Enabled?: boolean;
  productBasedMetric3Value?: string;
  productBasedMetric3Unit?: string;
  productBasedMetric3Title?: string;
  productBasedMetric3Subtitle?: string;
  productBasedMetric4Enabled?: boolean;
  productBasedMetric4Value?: string;
  productBasedMetric4Unit?: string;
  productBasedMetric4Title?: string;
  productBasedMetric4Subtitle?: string;
  productBasedMetric5Enabled?: boolean;
  productBasedMetric5Value?: string;
  productBasedMetric5Unit?: string;
  productBasedMetric5Title?: string;
  productBasedMetric5Subtitle?: string;
  productBasedMetric6Enabled?: boolean;
  productBasedMetric6Value?: string;
  productBasedMetric6Unit?: string;
  productBasedMetric6Title?: string;
  productBasedMetric6Subtitle?: string;
  productBasedMaxWidth?: number;
  productBasedPaddingTop?: number;
  productBasedPaddingBottom?: number;
  productBasedGridGap?: number;
  productBasedCircleSize?: number;
  productBasedCircleSpacing?: number;
  productBasedDesktopColumns?: number;
  productBasedTabletColumns?: number;
  productBasedValueFontSize?: number;
  productBasedUnitFontSize?: number;
  productBasedTitleFontSize?: number;
  productBasedSubtitleFontSize?: number;
  productBasedBackgroundColor?: string;
  productBasedTextColor?: string;
  productBasedMutedTextColor?: string;
  productBasedCircleColor?: string;
  productBasedCircleTextColor?: string;
  /** Sayfa içi link için id. Boş bırakılabilir. */
  sectionAnchorId?: string;
  /** En fazla 6 metrik render edilir. */
  metricCount?: number;
  metric1Enabled?: boolean;
  metric1Value?: string;
  metric1Unit?: string;
  metric1Title?: string;
  metric1Subtitle?: string;
  metric2Enabled?: boolean;
  metric2Value?: string;
  metric2Unit?: string;
  metric2Title?: string;
  metric2Subtitle?: string;
  metric3Enabled?: boolean;
  metric3Value?: string;
  metric3Unit?: string;
  metric3Title?: string;
  metric3Subtitle?: string;
  metric4Enabled?: boolean;
  metric4Value?: string;
  metric4Unit?: string;
  metric4Title?: string;
  metric4Subtitle?: string;
  metric5Enabled?: boolean;
  metric5Value?: string;
  metric5Unit?: string;
  metric5Title?: string;
  metric5Subtitle?: string;
  metric6Enabled?: boolean;
  metric6Value?: string;
  metric6Unit?: string;
  metric6Title?: string;
  metric6Subtitle?: string;
  maxWidth?: number;
  paddingTop?: number;
  paddingBottom?: number;
  gridGap?: number;
  circleSize?: number;
  circleSpacing?: number;
  desktopColumns?: number;
  tabletColumns?: number;
  valueFontSize?: number;
  unitFontSize?: number;
  titleFontSize?: number;
  subtitleFontSize?: number;
  backgroundColor?: string;
  textColor?: string;
  mutedTextColor?: string;
  circleColor?: string;
  circleTextColor?: string;
}
