import type { IkasImage, IkasProduct } from "@ikas/bp-storefront";

export type Props = {
  product?: IkasProduct;
  sectionIndex?: string;
  sectionLabel?: string;
  titleHtml?: string;
  sideHtml?: string;
  packageImage?: IkasImage | string;
  packageImageAlt?: string;
  packageBadge?: string;
  packageTitle?: string;
  packageSubtitle?: string;
  item1Number?: string;
  item1Title?: string;
  item1Description?: string;
  item1Tag?: string;
  item2Number?: string;
  item2Title?: string;
  item2Description?: string;
  item2Tag?: string;
  item3Number?: string;
  item3Title?: string;
  item3Description?: string;
  item3Tag?: string;
  item4Number?: string;
  item4Title?: string;
  item4Description?: string;
  item4Tag?: string;
  item5Number?: string;
  item5Title?: string;
  item5Description?: string;
  item5Tag?: string;
  item6Number?: string;
  item6Title?: string;
  item6Description?: string;
  item6Tag?: string;
  bottomBannerTitle?: string;
  bottomBannerText?: string;
  bottomBannerBadge?: string;
  ctaText?: string;
  ctaHref?: string;
};
