// This file is auto-generated — do not edit manually.
import type { IkasImage } from "@ikas/bp-storefront";

export interface Props {
  eyebrowText?: string;
  titleText?: string;
  descriptionHtml?: string;
  card1Title?: string;
  card1Text?: string;
  card2Title?: string;
  card2Text?: string;
  card3Title?: string;
  card3Text?: string;
  primaryButtonText?: string;
  primaryButtonHref?: string;
  secondaryButtonText?: string;
  secondaryButtonHref?: string;
  backgroundColor?: string;
  textColor?: string;
  mutedTextColor?: string;
  panelColor?: string;
  accentColor?: string;
  lineColor?: string;
  wordStyleEnabled?: boolean;
  styledPhrase?: string;
  styledPhraseColor?: string;
  styledPhraseBold?: boolean;
  styledPhraseItalic?: boolean;
  quoteAuthorText?: string;
  introTitleText?: string;
  /** Canlı Mash Academy sayfasındaki sağ büyük görsel. */
  introImageUrl?: IkasImage | null;
  introImageAlt?: string;
  showIntroImage?: boolean;
  event1ImageUrl?: IkasImage | null;
  event1ImageAlt?: string;
  event1Date?: string;
  event2ImageUrl?: IkasImage | null;
  event2ImageAlt?: string;
  event2Date?: string;
  showPastSection?: boolean;
  showEventCards?: boolean;
  headingColor?: string;
  cardTitleColor?: string;
  maxContentWidth?: number;
  eventCardsGap?: number;
  showQuoteSection?: boolean;
  showIntroSection?: boolean;
  event3Text?: string;
  event3ImageUrl?: IkasImage | null;
  event3ImageAlt?: string;
  event4Title?: string;
  event4Text?: string;
  event4ImageUrl?: IkasImage | null;
  event4ImageAlt?: string;
  event4Date?: string;
  event4Href?: string;
  showEvent4?: boolean;
  eyebrowTextEn?: string;
  titleTextEn?: string;
  descriptionHtmlEn?: string;
  card1TitleEn?: string;
  card1TextEn?: string;
  card2TitleEn?: string;
  card2TextEn?: string;
  card3TitleEn?: string;
  card3TextEn?: string;
  primaryButtonTextEn?: string;
  secondaryButtonTextEn?: string;
  introTitleTextEn?: string;
  introImageAltEn?: string;
  event1ImageAltEn?: string;
  event1DateEn?: string;
  event2ImageAltEn?: string;
  event2DateEn?: string;
  event3TitleEn?: string;
  event3TextEn?: string;
  event3ImageAltEn?: string;
  event4TitleEn?: string;
  event4TextEn?: string;
  event4ImageAltEn?: string;
  showEvent1?: boolean;
  showEvent2?: boolean;
  event3Title?: string;
  event3Date?: string;
  event3Href?: string;
  showEvent3?: boolean;
}
