// This file is auto-generated — do not edit manually.
import type { IkasImage } from "@ikas/bp-storefront";

export interface Props {
  sectionIndex?: string;
  sectionLabel?: string;
  titleHtml?: string;
  sideHtml?: string;
  showImages?: boolean;
  cert1ShowImage?: boolean;
  cert1Image?: IkasImage | null;
  cert1Badge?: string;
  cert1Title?: string;
  cert1Subtitle?: string;
  cert1ReportNo?: string;
  cert1Issuer?: string;
  cert1ActionText?: string;
  cert1ActionHref?: string;
  cert2ShowImage?: boolean;
  cert2Image?: IkasImage | null;
  cert2Badge?: string;
  cert2Title?: string;
  cert2Subtitle?: string;
  cert2ReportNo?: string;
  cert2Issuer?: string;
  cert2ActionText?: string;
  cert2ActionHref?: string;
  cert3ShowImage?: boolean;
  cert3Image?: IkasImage | null;
  cert3Badge?: string;
  cert3Title?: string;
  cert3Subtitle?: string;
  cert3ReportNo?: string;
  cert3Issuer?: string;
  cert3ActionText?: string;
  cert3ActionHref?: string;
  cert4ShowImage?: boolean;
  cert4Image?: IkasImage | null;
  cert4Badge?: string;
  cert4Title?: string;
  cert4Subtitle?: string;
  cert4ReportNo?: string;
  cert4Issuer?: string;
  cert4ActionText?: string;
  cert4ActionHref?: string;
  complianceNotice?: string;
  sectionLabelEn?: string;
  titleHtmlEn?: string;
  sideHtmlEn?: string;
  showCert1?: boolean;
  cert1BadgeEn?: string;
  cert1TitleEn?: string;
  cert1SubtitleEn?: string;
  cert1IssuerEn?: string;
  cert1ActionTextEn?: string;
  showCert2?: boolean;
  cert2BadgeEn?: string;
  cert2TitleEn?: string;
  cert2SubtitleEn?: string;
  cert2IssuerEn?: string;
  cert2ActionTextEn?: string;
  showCert3?: boolean;
  cert3BadgeEn?: string;
  cert3TitleEn?: string;
  cert3SubtitleEn?: string;
  cert3IssuerEn?: string;
  cert3ActionTextEn?: string;
  showCert4?: boolean;
  cert4BadgeEn?: string;
  cert4TitleEn?: string;
  cert4SubtitleEn?: string;
  cert4IssuerEn?: string;
  cert4ActionTextEn?: string;
  reportNoLabel?: string;
  reportNoLabelEn?: string;
  issuerLabel?: string;
  issuerLabelEn?: string;
  complianceNoticeEn?: string;
  showComplianceNotice?: boolean;
  cert1ReportNoEn?: string;
  cert2ReportNoEn?: string;
  cert3ReportNoEn?: string;
  cert4ReportNoEn?: string;
}
