// This file is auto-generated — do not edit manually.
import type { IkasImage } from "@ikas/bp-storefront";

export interface Props {
  sectionAnchorId?: string;
  eyebrowText?: string;
  titleText?: string;
  descriptionHtml?: string;
  primaryButtonText?: string;
  primaryButtonHref?: string;
  secondaryButtonText?: string;
  secondaryButtonHref?: string;
  backgroundColor?: string;
  textColor?: string;
  mutedTextColor?: string;
  lineColor?: string;
  maxWidth?: number;
  paddingTop?: number;
  paddingBottom?: number;
  eyebrowTextEn?: string;
  titleTextEn?: string;
  descriptionHtmlEn?: string;
  primaryButtonTextEn?: string;
  secondaryButtonTextEn?: string;
  proofEyebrow?: string;
  proofEyebrowEn?: string;
  proofTitle?: string;
  proofTitleEn?: string;
  proofDescription?: string;
  proofDescriptionEn?: string;
  proofCategory1?: string;
  proofCategory1En?: string;
  proofCategory2?: string;
  proofCategory2En?: string;
  proofCategory3?: string;
  proofCategory3En?: string;
  proofCategory4?: string;
  proofCategory4En?: string;
  proofMetric1Value?: string;
  proofMetric1Label?: string;
  proofMetric1LabelEn?: string;
  proofMetric2Value?: string;
  proofMetric2Label?: string;
  proofMetric2LabelEn?: string;
  proofMetric3Value?: string;
  proofMetric3Label?: string;
  proofMetric3LabelEn?: string;
  actionsAriaLabel?: string;
  actionsAriaLabelEn?: string;
  proofAriaLabel?: string;
  proofAriaLabelEn?: string;
  logosAriaLabel?: string;
  logosAriaLabelEn?: string;
  referencesAriaLabel?: string;
  referencesAriaLabelEn?: string;
  showActions?: boolean;
  showProofSummary?: boolean;
  showTrustLogos?: boolean;
  showReferenceWall?: boolean;
  showCaseStudy?: boolean;
  showPartners?: boolean;
  showWorkflow?: boolean;
  showPrimaryButton?: boolean;
  showSecondaryButton?: boolean;
  trustLogo1ImageUrl?: IkasImage | null;
  trustLogo2ImageUrl?: IkasImage | null;
  trustLogo3ImageUrl?: IkasImage | null;
  trustLogo4ImageUrl?: IkasImage | null;
  trustLogo5ImageUrl?: IkasImage | null;
  reference1TypeText?: string;
  reference1TypeTextEn?: string;
  reference1QuoteHtml?: string;
  reference1QuoteHtmlEn?: string;
  reference1NameText?: string;
  reference1NameTextEn?: string;
  reference1DetailsHtml?: string;
  reference1DetailsHtmlEn?: string;
  reference1ImageUrl?: IkasImage | null;
  showReference1?: boolean;
  reference2TypeText?: string;
  reference2TypeTextEn?: string;
  reference2QuoteHtml?: string;
  reference2QuoteHtmlEn?: string;
  reference2NameText?: string;
  reference2NameTextEn?: string;
  reference2DetailsHtml?: string;
  reference2DetailsHtmlEn?: string;
  reference2ImageUrl?: IkasImage | null;
  showReference2?: boolean;
  reference3TypeText?: string;
  reference3TypeTextEn?: string;
  reference3QuoteHtml?: string;
  reference3QuoteHtmlEn?: string;
  reference3NameText?: string;
  reference3NameTextEn?: string;
  reference3DetailsHtml?: string;
  reference3DetailsHtmlEn?: string;
  reference3ImageUrl?: IkasImage | null;
  showReference3?: boolean;
  reference4TypeText?: string;
  reference4TypeTextEn?: string;
  reference4QuoteHtml?: string;
  reference4QuoteHtmlEn?: string;
  reference4NameText?: string;
  reference4NameTextEn?: string;
  reference4DetailsHtml?: string;
  reference4DetailsHtmlEn?: string;
  reference4ImageUrl?: IkasImage | null;
  showReference4?: boolean;
  reference5TypeText?: string;
  reference5TypeTextEn?: string;
  reference5QuoteHtml?: string;
  reference5QuoteHtmlEn?: string;
  reference5NameText?: string;
  reference5NameTextEn?: string;
  reference5DetailsHtml?: string;
  reference5DetailsHtmlEn?: string;
  reference5ImageUrl?: IkasImage | null;
  showReference5?: boolean;
  reference6TypeText?: string;
  reference6TypeTextEn?: string;
  reference6QuoteHtml?: string;
  reference6QuoteHtmlEn?: string;
  reference6NameText?: string;
  reference6NameTextEn?: string;
  reference6DetailsHtml?: string;
  reference6DetailsHtmlEn?: string;
  reference6ImageUrl?: IkasImage | null;
  showReference6?: boolean;
  reference7TypeText?: string;
  reference7TypeTextEn?: string;
  reference7QuoteHtml?: string;
  reference7QuoteHtmlEn?: string;
  reference7NameText?: string;
  reference7NameTextEn?: string;
  reference7DetailsHtml?: string;
  reference7DetailsHtmlEn?: string;
  reference7ImageUrl?: IkasImage | null;
  showReference7?: boolean;
  reference8TypeText?: string;
  reference8TypeTextEn?: string;
  reference8QuoteHtml?: string;
  reference8QuoteHtmlEn?: string;
  reference8NameText?: string;
  reference8NameTextEn?: string;
  reference8DetailsHtml?: string;
  reference8DetailsHtmlEn?: string;
  reference8ImageUrl?: IkasImage | null;
  showReference8?: boolean;
  reference9TypeText?: string;
  reference9TypeTextEn?: string;
  reference9QuoteHtml?: string;
  reference9QuoteHtmlEn?: string;
  reference9NameText?: string;
  reference9NameTextEn?: string;
  reference9DetailsHtml?: string;
  reference9DetailsHtmlEn?: string;
  reference9ImageUrl?: IkasImage | null;
  showReference9?: boolean;
  reference10TypeText?: string;
  reference10TypeTextEn?: string;
  reference10QuoteHtml?: string;
  reference10QuoteHtmlEn?: string;
  reference10NameText?: string;
  reference10NameTextEn?: string;
  reference10DetailsHtml?: string;
  reference10DetailsHtmlEn?: string;
  reference10ImageUrl?: IkasImage | null;
  showReference10?: boolean;
  reference11TypeText?: string;
  reference11TypeTextEn?: string;
  reference11QuoteHtml?: string;
  reference11QuoteHtmlEn?: string;
  reference11NameText?: string;
  reference11NameTextEn?: string;
  reference11DetailsHtml?: string;
  reference11DetailsHtmlEn?: string;
  reference11ImageUrl?: IkasImage | null;
  showReference11?: boolean;
  caseKicker?: string;
  caseKickerEn?: string;
  caseTitle?: string;
  caseTitleEn?: string;
  caseDescription?: string;
  caseDescriptionEn?: string;
  caseImageAlt?: string;
  caseImageAltEn?: string;
  caseCaptionTitle?: string;
  caseCaptionTitleEn?: string;
  caseCaptionText?: string;
  caseCaptionTextEn?: string;
  caseImageUrl?: IkasImage | null;
  storyPoint1Text?: string;
  storyPoint1TextEn?: string;
  showStoryPoint1?: boolean;
  storyPoint2Text?: string;
  storyPoint2TextEn?: string;
  showStoryPoint2?: boolean;
  storyPoint3Text?: string;
  storyPoint3TextEn?: string;
  showStoryPoint3?: boolean;
  storyPoint4Text?: string;
  storyPoint4TextEn?: string;
  showStoryPoint4?: boolean;
  storyPoint5Text?: string;
  storyPoint5TextEn?: string;
  showStoryPoint5?: boolean;
  partner1NameText?: string;
  partner1NameTextEn?: string;
  partner1TitleText?: string;
  partner1TitleTextEn?: string;
  partner1DescriptionHtml?: string;
  partner1DescriptionHtmlEn?: string;
  partner1ImageUrl?: IkasImage | null;
  showPartner1?: boolean;
  partner2NameText?: string;
  partner2NameTextEn?: string;
  partner2TitleText?: string;
  partner2TitleTextEn?: string;
  partner2DescriptionHtml?: string;
  partner2DescriptionHtmlEn?: string;
  partner2ImageUrl?: IkasImage | null;
  showPartner2?: boolean;
  partner3NameText?: string;
  partner3NameTextEn?: string;
  partner3TitleText?: string;
  partner3TitleTextEn?: string;
  partner3DescriptionHtml?: string;
  partner3DescriptionHtmlEn?: string;
  partner3ImageUrl?: IkasImage | null;
  showPartner3?: boolean;
  workflowKicker?: string;
  workflowKickerEn?: string;
  workflowTitle?: string;
  workflowTitleEn?: string;
  workflowDescription?: string;
  workflowDescriptionEn?: string;
  workflow1TitleText?: string;
  workflow1TitleTextEn?: string;
  workflow1DescriptionHtml?: string;
  workflow1DescriptionHtmlEn?: string;
  workflow1ImageUrl?: IkasImage | null;
  showWorkflowCard1?: boolean;
  workflow2TitleText?: string;
  workflow2TitleTextEn?: string;
  workflow2DescriptionHtml?: string;
  workflow2DescriptionHtmlEn?: string;
  workflow2ImageUrl?: IkasImage | null;
  showWorkflowCard2?: boolean;
  workflow3TitleText?: string;
  workflow3TitleTextEn?: string;
  workflow3DescriptionHtml?: string;
  workflow3DescriptionHtmlEn?: string;
  workflow3ImageUrl?: IkasImage | null;
  showWorkflowCard3?: boolean;
  workflow4TitleText?: string;
  workflow4TitleTextEn?: string;
  workflow4DescriptionHtml?: string;
  workflow4DescriptionHtmlEn?: string;
  workflow4ImageUrl?: IkasImage | null;
  showWorkflowCard4?: boolean;
  partnersKicker?: string;
  partnersKickerEn?: string;
  partnersTitle?: string;
  partnersTitleEn?: string;
}
