// This file is auto-generated — do not edit manually.
import type { IkasImage } from "@ikas/bp-storefront";
import type { LogoImageFit } from "../../global-types";

export interface Props {
  sectionAnchorId?: string;
  indexNumber?: string;
  indexText?: string;
  titleText?: string;
  titleEmphasis?: string;
  sideHtml?: string;
  reason1Eyebrow?: string;
  reason1Title?: string;
  reason1DescriptionHtml?: string;
  reason2Eyebrow?: string;
  reason2Title?: string;
  reason2DescriptionHtml?: string;
  reason3Eyebrow?: string;
  reason3Title?: string;
  reason3DescriptionHtml?: string;
  curingProduct1Tag?: string;
  curingProduct1Title?: string;
  curingProduct1DescriptionHtml?: string;
  /** Upload a replacement product image. If empty, the bundled product image is used. */
  curingProduct1ImageUrl?: IkasImage | null;
  curingProduct1ImageAlt?: string;
  curingProduct1Spec1Label?: string;
  curingProduct1Spec1Value?: string;
  curingProduct1Spec2Label?: string;
  curingProduct1Spec2Value?: string;
  curingProduct1CtaText?: string;
  curingProduct1CtaHref?: string;
  curingProduct2Tag?: string;
  curingProduct2Title?: string;
  curingProduct2DescriptionHtml?: string;
  /** Upload a replacement product image. If empty, the bundled product image is used. */
  curingProduct2ImageUrl?: IkasImage | null;
  curingProduct2ImageAlt?: string;
  curingProduct2Spec1Label?: string;
  curingProduct2Spec1Value?: string;
  curingProduct2Spec2Label?: string;
  curingProduct2Spec2Value?: string;
  curingProduct2CtaText?: string;
  curingProduct2CtaHref?: string;
  productImageWidth?: number;
  productImageHeight?: number;
  productImageXOffset?: number;
  productImageYOffset?: number;
  productImageFit?: LogoImageFit;
  productImageOpacity?: number;
  productImageBrightness?: number;
  productImageContrast?: number;
  productImageSaturation?: number;
  productImageHue?: number;
  productImageInvert?: number;
  readMoreText?: string;
  readMoreLink1Text?: string;
  readMoreLink1Href?: string;
  readMoreLink2Text?: string;
  readMoreLink2Href?: string;
  backgroundColor?: string;
  textColor?: string;
  subTextColor?: string;
  mutedTextColor?: string;
  lineColor?: string;
  panelColor?: string;
  darkColor?: string;
  accentColor?: string;
  accentTextColor?: string;
  accentSoftColor?: string;
  dangerColor?: string;
  reasonCardBackgroundColor?: string;
  productMediaStartColor?: string;
  productMediaEndColor?: string;
  reasonCardRadius?: number;
  productCardRadius?: number;
}
