// This file is auto-generated — do not edit manually.
import type { IkasProduct, IkasImage } from "@ikas/bp-storefront";
import type { LogoImageFit } from "../../global-types";

export interface Props {
  /** Ürün seçildiğinde kartın ana verileri canlı ikas ürününden alınır. Boş bırakılırsa bu kart grubundaki manuel metinler ve görsel kullanılır. */
  curingProduct1Product?: IkasProduct | null;
  /** Ürün seçildiğinde kartın ana verileri canlı ikas ürününden alınır. Boş bırakılırsa bu kart grubundaki manuel metinler ve görsel kullanılır. */
  curingProduct2Product?: IkasProduct | null;
  sectionAnchorId?: string;
  indexNumber?: string;
  indexText?: string;
  titleText?: string;
  titleEmphasis?: string;
  sideHtml?: string;
  reason1Eyebrow?: string;
  reason1Title?: string;
  reason1DescriptionHtml?: string;
  reason2Eyebrow?: string;
  reason2Title?: string;
  reason2DescriptionHtml?: string;
  reason3Eyebrow?: string;
  reason3Title?: string;
  reason3DescriptionHtml?: string;
  curingProduct1Tag?: string;
  curingProduct1Title?: string;
  curingProduct1DescriptionHtml?: string;
  /** Canlı ürün görseli yoksa bu görsel kullanılır; ürün seçilmemişse paketli görselin yerine geçer. */
  curingProduct1ImageUrl?: IkasImage | null;
  curingProduct1ImageAlt?: string;
  curingProduct1Spec1Label?: string;
  curingProduct1Spec1Value?: string;
  curingProduct1Spec2Label?: string;
  curingProduct1Spec2Value?: string;
  curingProduct1CtaText?: string;
  curingProduct1CtaHref?: string;
  curingProduct2Tag?: string;
  curingProduct2Title?: string;
  curingProduct2DescriptionHtml?: string;
  /** Canlı ürün görseli yoksa bu görsel kullanılır; ürün seçilmemişse paketli görselin yerine geçer. */
  curingProduct2ImageUrl?: IkasImage | null;
  curingProduct2ImageAlt?: string;
  curingProduct2Spec1Label?: string;
  curingProduct2Spec1Value?: string;
  curingProduct2Spec2Label?: string;
  curingProduct2Spec2Value?: string;
  curingProduct2CtaText?: string;
  curingProduct2CtaHref?: string;
  productImageWidth?: number;
  productImageHeight?: number;
  productImageXOffset?: number;
  productImageYOffset?: number;
  productImageFit?: LogoImageFit;
  productImageOpacity?: number;
  productImageBrightness?: number;
  productImageContrast?: number;
  productImageSaturation?: number;
  productImageHue?: number;
  productImageInvert?: number;
  readMoreText?: string;
  readMoreLink1Text?: string;
  readMoreLink1Href?: string;
  readMoreLink2Text?: string;
  readMoreLink2Href?: string;
  backgroundColor?: string;
  textColor?: string;
  subTextColor?: string;
  mutedTextColor?: string;
  lineColor?: string;
  panelColor?: string;
  accentColor?: string;
  accentTextColor?: string;
  accentSoftColor?: string;
  reasonCardBackgroundColor?: string;
  productMediaStartColor?: string;
  productMediaEndColor?: string;
  reasonCardRadius?: number;
  productCardRadius?: number;
  wordStyleEnabled?: boolean;
  styledPhrase?: string;
  styledPhraseColor?: string;
  styledPhraseBold?: boolean;
  styledPhraseItalic?: boolean;
  indexTextEn?: string;
  titleTextEn?: string;
  titleEmphasisEn?: string;
  sideHtmlEn?: string;
  reason1EyebrowEn?: string;
  reason1TitleEn?: string;
  reason1DescriptionHtmlEn?: string;
  reason2EyebrowEn?: string;
  reason2TitleEn?: string;
  reason2DescriptionHtmlEn?: string;
  reason3EyebrowEn?: string;
  reason3TitleEn?: string;
  reason3DescriptionHtmlEn?: string;
  curingProduct1TagEn?: string;
  curingProduct1TitleEn?: string;
  curingProduct1DescriptionHtmlEn?: string;
  curingProduct1ImageAltEn?: string;
  curingProduct1Spec1LabelEn?: string;
  curingProduct1Spec1ValueEn?: string;
  curingProduct1Spec2LabelEn?: string;
  curingProduct1Spec2ValueEn?: string;
  curingProduct1CtaTextEn?: string;
  curingProduct2TagEn?: string;
  curingProduct2TitleEn?: string;
  curingProduct2DescriptionHtmlEn?: string;
  curingProduct2ImageAltEn?: string;
  curingProduct2Spec1LabelEn?: string;
  curingProduct2Spec1ValueEn?: string;
  curingProduct2Spec2LabelEn?: string;
  curingProduct2Spec2ValueEn?: string;
  curingProduct2CtaTextEn?: string;
  readMoreTextEn?: string;
  readMoreLink1TextEn?: string;
  readMoreLink2TextEn?: string;
  dynamicPriceLabel?: string;
  dynamicListPriceLabel?: string;
  dynamicBrandLabel?: string;
  dynamicCategoryLabel?: string;
  dynamicPriceLabelEn?: string;
  dynamicListPriceLabelEn?: string;
  dynamicBrandLabelEn?: string;
  dynamicCategoryLabelEn?: string;
  showReason1?: boolean;
  showReason2?: boolean;
  showReason3?: boolean;
  showProduct1?: boolean;
  showProduct2?: boolean;
  showReadMore?: boolean;
  showReadMoreLink1?: boolean;
  showReadMoreLink2?: boolean;
}
