// This file is auto-generated — do not edit manually.
import type { IkasImage } from "@ikas/bp-storefront";

export interface Props {
  brandLabel?: string;
  brandLabelEn?: string;
  pageTitle?: string;
  pageTitleEn?: string;
  pageDescription?: string;
  pageDescriptionEn?: string;
  quoteHeadingHtml?: string;
  quoteHeadingHtmlEn?: string;
  quoteHtml?: string;
  quoteHtmlEn?: string;
  storyHtml?: string;
  storyHtmlEn?: string;
  missionVisionHtml?: string;
  missionVisionHtmlEn?: string;
  valuesHeading?: string;
  valuesHeadingEn?: string;
  storyImageAlt?: string;
  storyImageAltEn?: string;
  missionVisionImageAlt?: string;
  missionVisionImageAltEn?: string;
  principle1Title?: string;
  principle1TitleEn?: string;
  principle1Description?: string;
  principle1DescriptionEn?: string;
  principle1ImageAlt?: string;
  principle1ImageAltEn?: string;
  principle2Title?: string;
  principle2TitleEn?: string;
  principle2Description?: string;
  principle2DescriptionEn?: string;
  principle2ImageAlt?: string;
  principle2ImageAltEn?: string;
  principle3Title?: string;
  principle3TitleEn?: string;
  principle3Description?: string;
  principle3DescriptionEn?: string;
  principle3ImageAlt?: string;
  principle3ImageAltEn?: string;
  principle4Title?: string;
  principle4TitleEn?: string;
  principle4Description?: string;
  principle4DescriptionEn?: string;
  principle4ImageAlt?: string;
  principle4ImageAltEn?: string;
  storyImage?: IkasImage | null;
  missionVisionImage?: IkasImage | null;
  principle1Image?: IkasImage | null;
  principle2Image?: IkasImage | null;
  principle3Image?: IkasImage | null;
  principle4Image?: IkasImage | null;
  backgroundColor?: string;
  headingColor?: string;
  accentColor?: string;
  /** Piksel cinsinden; 720–1800 arası. */
  contentWidth?: number;
  showIntroduction?: boolean;
  showStory?: boolean;
  showPrinciple1?: boolean;
  showPrinciple2?: boolean;
  showPrinciple3?: boolean;
  showPrinciple4?: boolean;
  bodyColor?: string;
  secondaryTextColor?: string;
  showMissionAndVision?: boolean;
  showPrinciples?: boolean;
}
